### PR TITLE
Add option to drink antidote potions before Lilith in OrgTorch

### PR DESCRIPTION
**Pull request by jmichelsen**
While not necessary, I find being able to up my poison resist just for Lilith gives me peace of mind that my guy won't accidentally die :)

### CODE REVIEW

**Comment by jaenster** [comment]
Good idea, i like that you made it as a separated function, so it can be used on other places as well.

What is a bit silly trough is that it goes in side of the portal, after that to town (i assume with a tp) and after that, it goes back in the red portal once again.

Cant you make it, it takes the antidotes, just before taking the red portal? =)

**Comment by jmichelsen** [comment]
> Good idea, i like that you made it as a separated function, so it can be used on other places as well.
> 
> What is a bit silly trough is that it goes in side of the portal, after that to town (i assume with a tp) and after that, it goes back in the red portal once again.
> 
> Cant you make it, it takes the antidotes, just before taking the red portal? =)

Yea I didn't love that I had to do that but I couldn't find a way to know where the portal was heading before going through it. The main functionality of the OrgTorch.js script is the same way, it doesn't know which uber is being run until the char enters and `me.area` can be queried.

I could modify this to buy the antidotes first and then just consume them when `area.me == matronsden`. 

Thoughts? Do you know a way to see the portal target before entering, specifically with red portals?

**Comment by jaenster** [comment]
439,
```javascript
			if (portal) {
				Pather.usePortal(null, null, portal);
			}
```

Here you have the portal, and you can ask which area it leads too =)

**Comment by jmichelsen** [comment]
> 439,
> 
> ```js
> 			if (portal) {
> 				Pather.usePortal(null, null, portal);
> 			}
> ```
> 
> Here you have the portal, and you can ask which area it leads too =)

I tried using `portal.target` and `portal.area`..I was just guessing as to what attributes the portal object would have because I couldn't find the portal unit definition..looking a little deeper, it looks like the target area is housed in `portal.objtype`? I'll give that a try and move the antidotes up. Thanks for the feedback

**Pull request merged**
